system:
  domain : mall
  version : 1.0
  env : "dev"
  HttpPort: ":5001"
  Host: "localhost"
  UploadModel: "local"

mysql:
  default:
    dialect: "mysql"
    dbHost: "127.0.0.1"
    dbPort: "3306"
    dbName: "user_db"
    userName: "user"
    password: "user"
    charset: "utf8mb4"
    MaxIdleConns : 10
    MaxOpenConns : 100
    ConnMaxLifetime : 20
redis:
  redisDbName: 0
  redisHost: r-3ns7huz6q0teloxquw.redis.rds.aliyuncs.com
  redisPort: 6379
  redisUsername: front_risk_rw
  redisPassword: E4gb2ji580
  redisNetwork: "tcp"


encryptSecret:
  jwtSecret: "FanOne666Secret"
  emailSecret: "EmailSecret"
  phoneSecret: "PhoneSecret"
  
